''' LIWC Confidence Method '''

confidence_words = {'may' : +1, 'link' : -1, 'associate' : +1, 'causal' : +1, 
					'cause' : +1, 'create' : +1, 'relate' : 0, 'relation' : 0,
					'correlat' : 0, 'connect' : +1, 'suggest' : -1, 'indicat' : 0,
					'point' : 0, 'represent' : 0, 'display' : +1, 'expose' : +1,
					'unveil' : +1, 'uncover' : +1, 'discover' : +1, 'unearth' : +1,
					'invent' : +1, 'observ' : 0, 'prove' : +1, 'confirm' : +1,
					'affirm' : +1, 'assert' : +1, 'declar' : +1, 'proclaim' : +1,
					'guarantee' : +1, 'insure' : +1, 'assur' : +1, 'corroborat' : 0,
					'authentic' : +1, 'validate' : +1, 'endorse' : +1, 'defend' : +1,
					'conclud' : 0, 'support' : +1, 'verify' : +1, 'establish' : +1,
					'substantiate' : +1, 'try' : -1, 'tried' : -1, 'attempt' : -1,
					'demonstrat' : +1, 'describe' : 0, 'justif' : -1, 'reveal' : +1,
					'concede' : -1, 'admit' : -1, 'confess' : -1, 'acknowledg' : -1,
					'recogniz' : 0, 'solve' : +1, 'clarify' : 0, 'help' : -1,
					'further' : -1, 'explain' : +1, 'resolve' : +1, 'hope' : -1,
					'believe' : -1, 'illustrat' : 0, 'highlight' : 0, 'exhibit' : 0,
					'determin' : 0, 'promis' : 0, 'could' : -1, 'definitely' : +1,
					'clearly' : +1, 'absolutely' : +1, 'doubtless' : +1,'obvious' : +1,
					'plainly' : +1, 'surely' : +1, 'undeniabl' : +1, 'unequivocal' : +1,
					'unquestionabl' : +1, 'certain' : +1, '''or -1 if uncertain''' 'decisive' : +1, 'convincing' : +1,
					'definitive' : +1, 'find' : +1, 'detect' : +1, 'possibl' : 0, # uncertain root,
					'potential' : -1, 'doubt' : -1, 'does' : +1, 'perhaps' : -1,
					'show' : +1, 'predict' : +1, 'proof' : +1, 'identif' : +1,
					'significant' : +1, 'important' : +1, 'revolutionary' : +1, 'though' : -1,
					'valid' : +1, 'clear' : 0, '''clear and unclear''' 'agree' : 0, 'answer' : 0, # answer or unanswered
					'deriv' : 0, 'new' : 0, 'seem' : -1, 'appear' : -1,
					'limit' : -1, 'lead' : +1, 'led' : +1, 'creates' : 0,
					'found' : +1, 'report' : 0, 'impact' : 0, 'promis' : +1,
					'novel' : 0, 'improve': +1, 'likely' : -1, 'might' : -1,
					'probabl' : -1, 'success' : +1, 'tend' : -1, 'think' : -1,
					'assum' : -1, 'must' : -1, 'often' : -1, 'frequent' : -1,
					'sometime' : -1, 'usually' : -1, 'conceivably' : -1}